services:
  core:
    build:
      dockerfile: Dockerfile
    image: wiseflow:latest
    tty: true
    stdin_open: true
    entrypoint: ["bash", "/app/docker_entrypoint.sh"]
    ports:
      - 8095:8095
    volumes:
      - ./core:/app
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations